repos:

# Black formats Python files.
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      files: ^src/                              # Include all files within `src/`.
